language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm test
  - npm run coverage
before_script:
  - npm prune
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
after_success:
  - npx travis-deploy-once 'npm run semantic-release'
  - ./deploy.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
