language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
script:
  - npm test
  - npm run coverage
before_script:
  - npm prune
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
after_success:
  - npm run semantic-release
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
